version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: obsrv123
      POSTGRES_USER: postgres
      POSTGRES_DB : obsrv 
    # networks:
    # - api  
    ports:
    - "5432:5432"
    volumes:
    - volumne_one:/var/lib/postgresql/data/
    - ./postgres:/docker-entrypoint-initdb.d


  app:
    image: cruidapi-app
    build: 
      context: .
    environment:
      password: obsrv123
      user: obsrv_user
      database : obsrv   
      host: db
    depends_on:
      - db
    # networks:
    #   - api
    ports:
      - "3000:3000"
# networks:
#   api:
#     driver: bridge

volumes:
  volumne_one:

  